### ISSUE TITLE
Online and More Options are Stuck Loading

### ISSUE THREAD

**Issue by evan203** [batram/UCH-EvenMorePlayers#15]
I am running arch linux `6.4.1-arch1-1`.  
Steam Version: 1688428930
MorePlayersMod-0.9.0.2
BepInEx_unix_5.4.21.0
![image](https://github.com/batram/UCH-EvenMorePlayers/assets/63885438/e4392520-44d7-4015-b1fa-3832a8bad72f)
When launching the game from the run_bepinex.sh script, a loading animation endlessly spins over greyed out online and more buttons.  
A friend of mine on artix is experiencing the same issue.

**Comment by batram** [comment]
Thanks for the report, in most cases in the past discussed on the [discord server](https://discord.gg/GgzDQW6zbq) this turned out to be an issue with the interplay of Steam and BepInEx.

You need to start the game through Steam for online play to work and it won't work by launching `run_bepenix.sh` directly.
For that you need to set the launch option in Steam:
https://docs.bepinex.dev/articles/advanced/steam_interop.html

There were also some issues with `run_bepenix.sh` in the past, that could be worked around by ignoring the `%command%` part.

![image](https://github.com/batram/UCH-EvenMorePlayers/assets/1382274/f7cde54f-2816-4f5a-8cb5-37a9d0d4678b)

**Comment by evan203** [comment]
Thanks for the quick feedback. I can update the readme for you when I have time. I tried changing the steam launch options to `./run_bepinex.sh %command%` however the game would not start and would immediately crash. I have not tried yet `./run_bepinex.sh; echo %command%`. Let me get back to you on this!
